/*****************************************************************************************
    Name             : SiteRegister_Test
    Description      : Main test class  to cover all Id scenarios in Buttons classes                 
    Modification Log : 
---------------------------------------------------------------------------
Developer              Date              Description
---------------------------------------------------------------------------
Subhojit                30/10/2014            Created
Subhojit                29/01/2015            Modified for code re-factoring & optimization
******************************************************************************************/
@isTest(SeeAllData=true)
public class SiteRegister_Test{

       static testMethod void SiteRegister_Test()
    {        
      
      SiteLoginController slController = new SiteLoginController();
      SiteRegisterController srController = new SiteRegisterController();
      
      
      }      
      
}