span.TwitterWrapper * {font-family:"Helvetica Neue", Arial, sans-serif; margin: 0px 2px 2px 2px; padding: 0; color:#333; font-size:medium; line-height:130%;}
span.TwitterWrapper a {text-decoration:none; color:#0084b4;}
span.TwitterWrapper a:hover {text-decoration:underline; color:#0084b4;}


span.TwitterWrapper .retweetIndicator {font-size:85%; font-weight:lighter; color:#999;}

span.TwitterWrapper .postAction .intentIcon {height:1em; width:1em; vertical-align:text-top;}
span.TwitterWrapper .retweetIndicator img {margin-right:0.25em;}
span.TwitterWrapper .retweetIndicator {display:block;}